import KimGeonRyeong_BW from '../assets/designer/kimgeonryeong/kimgeonryeong_bw.jpg'
import KimGeonRyeong_Color from '../assets/designer/kimgeonryeong/KimGeonRyeong_Color.jpg'



export const navLinks = [
    {
      id: "about",
      title: "ABOUT",
    },
    {
      id: "projects",
      title: "PROJECTS",
    },
    {
      id: "designers",
      title: "DESIGNERS",
    },
    {
        id: "visit",
        title: "VISIT",
      },
  ];

  const DesignersData ={
    KimGeonRyeong : {
      Name_kor : "김 건령",
      Name_eng : "KIM GEONRYEONG",
      Role : "Product designer",
      Email : "kasias9810@gmail.com",
      Link_insta : "",
      Link_Behance : "",
      Image_BW :KimGeonRyeong_BW,
      Image_Color:KimGeonRyeong_Color,  
    },
    KimGoEun:{
      Name_kor : "김 고은",
      Name_eng : "KIM GOEUN",
      Role : "Product designer",
      Email : "3470604@gmail.com",
      Link_insta : "",
      Link_Behance : "",
      Image_BW :KimGeonRyeong_BW,
      Image_Color:KimGeonRyeong_Color,  
    },
    KimDongJun:{
      Name_kor : "김동준",
      Name_eng : "KIM DONGJUN",
      Role : "3D Graphic designer",
      Email : "hellodongjun@gmail.com",
      Link_insta : "",
      Link_Behance : "",
      Image_BW :KimGeonRyeong_BW,
      Image_Color:KimGeonRyeong_Color,  
    },
    KimYaeJu:{
      Name_kor : "김 예주",
      Name_eng : "KIM YAEJU",
      Role : "Space designer",
      Email : "sally2629@naver.com",
      Link_insta : "",
      Link_Behance : "",
      Image_BW :KimGeonRyeong_BW,
      Image_Color:KimGeonRyeong_Color,  
    },
    KimYunHa:{
      Name_kor : "김 윤하",
      Name_eng : "KIM YUNHA",
      Role : "Space designer",
      Email : "ssp04322@gmail.com",
      Link_insta : "",
      Link_Behance : "",
      Image_BW :KimGeonRyeong_BW,
      Image_Color:KimGeonRyeong_Color,  
    },
    KimJiHwan:{
      Name_kor : "김 지환",
      Name_eng : "KIM YAEJU",
      Role : "Graphic designer",
      Email : "kioo3022@naver.com",
      Link_insta : "",
      Link_Behance : "",
      Image_BW :KimGeonRyeong_BW,
      Image_Color:KimGeonRyeong_Color,  
    },
    NamMinJi:{
      Name_kor : "남 민지",
      Name_eng : "NAM MINJI",
      Role : "Space designer",
      Email : "rkfud724@naver.com",
      Link_insta : "",
      Link_Behance : "",
      Image_BW :KimGeonRyeong_BW,
      Image_Color:KimGeonRyeong_Color,  
    },
    ParkChangMin:{
      Name_kor : "박 창민",
      Name_eng : "PARK CHANGMIN",
      Role : "Transportation designer",
      Email : "changminp816@naver.com",
      Link_insta : "",
      Link_Behance : "",
      Image_BW :KimGeonRyeong_BW,
      Image_Color:KimGeonRyeong_Color,  
    },
    BakSeungEun:{
      Name_kor : "백 승은",
      Name_eng : "BAK SEUNGEUN",
      Role : "Product designer",
      Email : "sebaiktool@gmail.com",
      Link_insta : "",
      Link_Behance : "",
      Image_BW :KimGeonRyeong_BW,
      Image_Color:KimGeonRyeong_Color,  
    },
    SeoAReum:{
      Name_kor : "서 아름",
      Name_eng : "SEO AREUM",
      Role : "Spatial designer",
      Email : "sar981101@naver.com",
      Link_insta : "",
      Link_Behance : "",
      Image_BW :KimGeonRyeong_BW,
      Image_Color:KimGeonRyeong_Color,  
    },
    ShinDongYeop:{
      Name_kor : "신 동엽",
      Name_eng : "SHIN DONGYEOP",
      Role : "Graphic designer",
      Email : "waid9@naver.com",
      Link_insta : "",
      Link_Behance : "",
      Image_BW :KimGeonRyeong_BW,
      Image_Color:KimGeonRyeong_Color,  
    },
    ShinJiWoo:{
      Name_kor : "신 지우",
      Name_eng : "SHIN JIWOO",
      Role : "Product designer",
      Email : "jiwoo4401@gmail.com",
      Link_insta : "",
      Link_Behance : "",
      Image_BW :KimGeonRyeong_BW,
      Image_Color:KimGeonRyeong_Color,  
    },
    SimMinSeop:{
      Name_kor : "심 민섭",
      Name_eng : "SIM MINSEOP",
      Role : "Art Toy artist",
      Email : "owlfactory1009@naver.com",
      Link_insta : "",
      Link_Behance : "",
      Image_BW :KimGeonRyeong_BW,
      Image_Color:KimGeonRyeong_Color,  
    },
    AnMyoungJi:{
      Name_kor : "안 명지",
      Name_eng : "AN MYOUNGJI",
      Role : "Product designer",
      Email : "comfymj20@gmail.com",
      Link_insta : "",
      Link_Behance : "",
      Image_BW :KimGeonRyeong_BW,
      Image_Color:KimGeonRyeong_Color,  
    },
    YangJiWon:{
      Name_kor : "양 지원",
      Name_eng : "YANG JIWON",
      Role : "Space designer",
      Email : "csz5hj8979@gmail.com",
      Link_insta : "",
      Link_Behance : "",
      Image_BW :KimGeonRyeong_BW,
      Image_Color:KimGeonRyeong_Color,  
    },
    YangHyeSeon:{
      Name_kor : "양 혜선",
      Name_eng : "YANG HYESEON",
      Role : "Product designer",
      Email : "sju05030@naver.comm",
      Link_insta : "",
      Link_Behance : "",
      Image_BW :KimGeonRyeong_BW,
      Image_Color:KimGeonRyeong_Color,  
    },
    WonHanJu:{
      Name_kor : "원 한주",
      Name_eng : "WON HANJU",
      Role : "Product designer",
      Email : "wonhanjoo@gmail.com",
      Link_insta : "",
      Link_Behance : "",
      Image_BW :KimGeonRyeong_BW,
      Image_Color:KimGeonRyeong_Color,  
    },
    YooDongJae:{
      Name_kor : "유 동재",
      Name_eng : "YOO DONGJAE",
      Role : "Product designer",
      Email : "nlosnfin22@gmail.com",
      Link_insta : "",
      Link_Behance : "",
      Image_BW :KimGeonRyeong_BW,
      Image_Color:KimGeonRyeong_Color,  
    },
    YuAJung:{
      Name_kor : "유 아정",
      Name_eng : "YU AJUNG",
      Role : "Product designer",
      Email : "jujusj0421@naver.com",
      Link_insta : "",
      Link_Behance : "",
      Image_BW :KimGeonRyeong_BW,
      Image_Color:KimGeonRyeong_Color,  
    },
    YuJiHui:{
      Name_kor : "유 지희",
      Name_eng : "YU JIHUI",
      Role : "Product designer",
      Email : "sarahyou@icloud.com",
      Link_insta : "",
      Link_Behance : "",
      Image_BW :KimGeonRyeong_BW,
      Image_Color:KimGeonRyeong_Color,  
    },
    LeeJongWon:{
      Name_kor : "이 종원",
      Name_eng : "LEE JONGWON",
      Role : "Product designer",
      Email : "idojwlee@gmail.com",
      Link_insta : "",
      Link_Behance : "",
      Image_BW :KimGeonRyeong_BW,
      Image_Color:KimGeonRyeong_Color,  
    },
    LeeHongKyu:{
      Name_kor : "이 홍규",
      Name_eng : "LEE HONGKYU",
      Role : "Product designer",
      Email : "qwerty03096@gmail.com",
      Link_insta : "",
      Link_Behance : "",
      Image_BW :KimGeonRyeong_BW,
      Image_Color:KimGeonRyeong_Color,  
    },
    JangSeoJin:{
      Name_kor : "장 서진",
      Name_eng : "JANG SEOJIN",
      Role : "Product designer",
      Email : "seojinswork@gmail.com",
      Link_insta : "",
      Link_Behance : "",
      Image_BW :KimGeonRyeong_BW,
      Image_Color:KimGeonRyeong_Color,  
    },
    JunSeWon:{
      Name_kor : "전 세원",
      Name_eng : "JUN SEWON",
      Role : "Product designer",
      Email : "swjw0619@naver.com",
      Link_insta : "",
      Link_Behance : "",
      Image_BW :KimGeonRyeong_BW,
      Image_Color:KimGeonRyeong_Color,  
    },
    JuYoonWoo:{
      Name_kor : "주 윤우",
      Name_eng : "JU YOONWOO",
      Role : "3D Graphic designer",
      Email : "wndbsdn28@naver.com",
      Link_insta : "",
      Link_Behance : "",
      Image_BW :KimGeonRyeong_BW,
      Image_Color:KimGeonRyeong_Color,  
    },
    ChoiDaIn:{
      Name_kor : "최 다인",
      Name_eng : "CHOI DAIN",
      Role : "Product designer",
      Email : "dain2090@naver.com",
      Link_insta : "",
      Link_Behance : "",
      Image_BW :KimGeonRyeong_BW,
      Image_Color:KimGeonRyeong_Color,  
    },
    ChoiJaeHo:{
      Name_kor : "최 재호",
      Name_eng : "CHOI JAEHO",
      Role : "Product designer",
      Email : "zmsdkdlwogh@naver.com",
      Link_insta : "",
      Link_Behance : "",
      Image_BW :KimGeonRyeong_BW,
      Image_Color:KimGeonRyeong_Color,  
    },
    HwangJuHyeok:{
      Name_kor : "황 주혁",
      Name_eng : "HWANG JUHYEOK",
      Role : "Product designer",
      Email : "hyeok12267@gmail.com",
      Link_insta : "",
      Link_Behance : "",
      Image_BW :KimGeonRyeong_BW,
      Image_Color:KimGeonRyeong_Color,  
    },
    HongDongYoung:{
      Name_kor : "홍 동영",
      Name_eng : "HONG DONGYOUNG",
      Role : "Product designer",
      Email : "hy1527@gmail.com",
      Link_insta : "",
      Link_Behance : "",
      Image_BW :KimGeonRyeong_BW,
      Image_Color:KimGeonRyeong_Color,  
    },
    " ":{
      Name_kor : "홍 동영",
      Name_eng : "HONG DONGYOUNG",
      Role : "Product designer",
      Email : "hy1527@gmail.com",
      Link_insta : "",
      Link_Behance : "",
      Image_BW :KimGeonRyeong_BW,
      Image_Color:KimGeonRyeong_Color,  
    }
  }

  const AllDeisngersData = [
    "KimGeonRyeong",
    "KimGoEun",
    "KimDongJun",
    "KimYaeJu",
    "KimYunHa",
    "KimJiHwan",
    " ",
    "NamMinJi",
    "ParkChangMin",
    "BakSeungEun",
    "SeoAReum",
    "ShinDongYeop",
    "ShinJiWoo",
    "SimMinSeop",
    "AnMyoungJi",
    "YangJiWon",
    "YangHyeSeon",
    " ",
    "WonHanJu",
    "YooDongJae",
    "YuAJung",
    "YuJiHui",
    "LeeJongWon",
    "LeeHongKyu",
    "JangSeoJin",
    "JunSeWon",
    "JuYoonWoo",
    " ",
    "ChoiDaIn",
    "ChoiJaeHo",
    "HwangJuHyeok",
    "HongDongYoung",
    
  ]

  export {DesignersData, AllDeisngersData};