import KimGeonRyeong_Color from "../assets/designer/KimGeonRyeong/KimGeonRyeong_color.jpg";
import KimGoEun_Color from "../assets/designer/KimGoEun/KimGoEun_color.jpg.jpg";
import KimDongJun_Color from "../assets/designer/KimDongJun/KimDongJun_color.jpg";
import KimYaeJu_Color from "../assets/designer/KimYaeJu/KimYaeJu_color.jpg";
import KimYunHa_Color from "../assets/designer/KimYunHa/KimYunHa_color.jpg";
import KimJiHwan_Color from "../assets/designer/KimJiHwan/KimJiHwan_color.jpg";
import NamMinJi_Color from "../assets/designer/NamMinJi/NamMinJi_color.jpg";
import ParkChangMin_Color from "../assets/designer/ParkChangMin/ParkChangMin_color.jpg";
import BakSeungEun_Color from "../assets/designer/BakSeungEun/BakSeungEun_color.jpg";
import SeoAReum_Color from "../assets/designer/SeoAReum/SeoAReum_color.jpg";
import ShinDongYeop_Color from "../assets/designer/ShinDongYeop/ShinDongYeop_color.jpg";
import ShinJiWoo_Color from "../assets/designer/ShinJiWoo/ShinJiWoo_color.jpg";
import SimMinSeop_Color from "../assets/designer/SimMinSeop/SimMinSeop_color.jpg";
import AnMyoungJi_Color from "../assets/designer/AnMyoungJi/AnMyoungJi_color.jpg";
import YangJiWon_Color from "../assets/designer/YangJiWon/YangJiWon_color.jpg";
import YangHyeSeon_Color from "../assets/designer/YangHyeSeon/YangHyeSeon_color.jpg";
import WonHanJu_Color from "../assets/designer/WonHanJu/WonHanJu_color.jpg";
import YooDongJae_Color from "../assets/designer/YooDongJae/YooDongJae_color.jpg";
import YuAJung_Color from "../assets/designer/YuAJung/YuAJung_color.jpg";
import YuJiHui_Color from "../assets/designer/YuJiHui/YuJiHui_color.jpg";
import LeeJongWon_Color from "../assets/designer/LeeJongWon/LeeJongWon_color.jpg";
import LeeHongKyu_Color from "../assets/designer/LeeHongKyu/LeeHongKyu_color.jpg";
import JangSeoJin_Color from "../assets/designer/JangSeoJin/JangSeoJin_color.jpg";
import JunSeWon_Color from "../assets/designer/JunSeWon/JunSeWon_color.jpg";
import JuYoonWoo_Color from "../assets/designer/JuYoonWoo/JuYoonWoo_color.jpg";
import ChoiDaIn_Color from "../assets/designer/ChoiDaIn/ChoiDaIn_color.jpg";
import ChoiJaeHo_Color from "../assets/designer/ChoiJaeHo/ChoiJaeHo_color.jpg";
import HwangJuHyeok_Color from "../assets/designer/HwangJuHyeok/HwangJuHyeok_color.jpg";
import HongDongYoung_Color from "../assets/designer/HongDongYoung/HongDongYoung_color.jpg";

export const navLinks = [
  {
    id: "about",
    title: "ABOUT",
  },
  {
    id: "projects",
    title: "PROJECTS",
  },
  {
    id: "designers",
    title: "DESIGNERS",
  },
  {
    id: "visit",
    title: "VISIT",
  },
];

const DesignersData = {
  KimGeonRyeong: {
    Name_kor: "김 건령",
    Name_eng: "KIM GEONRYEONG",
    Role: "Product designer",
    Email: "kasias9810@gmail.com",
    Link_insta: "https://www.instagram.com/louivuit_gr/",
    Link_Behance: "",
    Link_Blog: "",
    Image_Color: KimGeonRyeong_Color,
  },
  KimGoEun: {
    Name_kor: "김 고은",
    Name_eng: "KIM GOEUN",
    Role: "Product designer",
    Email: "3470604@gmail.com",
    Link_insta: "https://www.instagram.com/eun_9.21/",
    Link_Behance: "",
    Link_Blog: "",
    Image_Color: KimGoEun_Color,
  },
  KimDongJun: {
    Name_kor: "김 동준",
    Name_eng: "KIM DONGJUN",
    Role: "3D Graphic designer",
    Email: "hellodongjun@gmail.com",
    Link_insta: "https://www.instagram.com/gundalssi_/",
    Link_Behance: "https://www.behance.net/gundalssi",
    Link_Blog: "",
    Image_Color: KimDongJun_Color,
  },
  KimYaeJu: {
    Name_kor: "김 예주",
    Name_eng: "KIM YAEJU",
    Role: "Space designer",
    Email: "sally2629@naver.com",
    Link_insta: "https://www.instagram.com/belle_la_official/",
    Link_Behance: "",
    Link_Blog: "",
    Image_Color: KimYaeJu_Color,
  },
  KimYunHa: {
    Name_kor: "김 윤하",
    Name_eng: "KIM YUNHA",
    Role: "Space designer",
    Email: "ssp04322@gmail.com",
    Link_insta: "https://www.instagram.com/silkstone_look/",
    Link_Behance: "",
    Link_Blog: "",
    Image_Color: KimYunHa_Color,
  },
  KimJiHwan: {
    Name_kor: "김 지환",
    Name_eng: "KIM YAEJU",
    Role: "Graphic designer",
    Email: "kioo3022@naver.com",
    Link_insta: "https://www.instagram.com/ji_on.33/",
    Link_Behance: "",
    Link_Blog: "",
    Image_Color: KimJiHwan_Color,
  },
  NamMinJi: {
    Name_kor: "남 민지",
    Name_eng: "NAM MINJI",
    Role: "Space designer",
    Email: "rkfud724@naver.com",
    Link_insta: "https://www.instagram.com/ryeong724/",
    Link_Behance: "",
    Link_Blog: "",
    Image_Color: NamMinJi_Color,
  },
  ParkChangMin: {
    Name_kor: "박 창민",
    Name_eng: "PARK CHANGMIN",
    Role: "Transportation designer",
    Email: "changminp816@naver.com",
    Link_insta: "https://www.instagram.com/qkrckdals_/",
    Link_Behance: "https://www.behance.net/changminp8c347",
    Link_Blog: "",
    Image_Color: ParkChangMin_Color,
  },
  BakSeungEun: {
    Name_kor: "백 승은",
    Name_eng: "BAK SEUNGEUN",
    Role: "Product designer",
    Email: "sebaiktool@gmail.com",
    Link_insta: "https://www.instagram.com/100seungeun100/",
    Link_Behance: "",
    Link_Blog: "",
    Image_Color: BakSeungEun_Color,
  },
  SeoAReum: {
    Name_kor: "서 아름",
    Name_eng: "SEO AREUM",
    Role: "Spatial designer",
    Email: "sar981101@naver.com",
    Link_insta: "https://www.instagram.com/dkfma_daily/",
    Link_Behance: "",
    Link_Blog: "",
    Image_Color: SeoAReum_Color,
  },
  ShinDongYeop: {
    Name_kor: "신 동엽",
    Name_eng: "SHIN DONGYEOP",
    Role: "Graphic designer",
    Email: "waid9@naver.com",
    Link_insta: "https://www.instagram.com/shin_dydydy/",
    Link_Behance: "https://www.behance.net/shindydy",
    Link_Blog: "",
    Image_Color: ShinDongYeop_Color,
  },
  ShinJiWoo: {
    Name_kor: "신 지우",
    Name_eng: "SHIN JIWOO",
    Role: "Product designer",
    Email: "jiwoo4401@gmail.com",
    Link_insta: "https://www.instagram.com/ziuly__/",
    Link_Behance: "https://www.instagram.com/owlfactory_official/",
    Link_Blog: "",
    Image_Color: ShinJiWoo_Color,
  },
  SimMinSeop: {
    Name_kor: "심 민섭",
    Name_eng: "SIM MINSEOP",
    Role: "Art Toy artist",
    Email: "owlfactory1009@naver.com",
    Link_insta: "https://www.instagram.com/owlfactory_official/",
    Link_Behance: "",
    Link_Blog: "https://www.owlfactory.co.kr/",
    Image_Color: SimMinSeop_Color,
  },
  AnMyoungJi: {
    Name_kor: "안 명지",
    Name_eng: "AN MYOUNGJI",
    Role: "Product designer",
    Email: "comfymj20@gmail.com",
    Link_insta: "",
    Link_Behance: "",
    Link_Blog: "",
    Image_Color: AnMyoungJi_Color,
  },
  YangJiWon: {
    Name_kor: "양 지원",
    Name_eng: "YANG JIWON",
    Role: "Space designer",
    Email: "csz5hj8979@gmail.com",
    Link_insta: "https://www.instagram.com/zionezero/",
    Link_Behance: "",
    Link_Blog: "",
    Image_Color: YangJiWon_Color,
  },
  YangHyeSeon: {
    Name_kor: "양 혜선",
    Name_eng: "YANG HYESEON",
    Role: "Product designer",
    Email: "sju05030@naver.comm",
    Link_insta: "https://www.instagram.com/heeeeysun/",
    Link_Behance: "",
    Link_Blog: "",
    Image_Color: YangHyeSeon_Color,
  },
  WonHanJu: {
    Name_kor: "원 한주",
    Name_eng: "WON HANJU",
    Role: "Product designer",
    Email: "wonhanjoo@gmail.com",
    Link_insta: "https://www.instagram.com/1hanj00/",
    Link_Behance: "",
    Link_Blog: "",
    Image_Color: WonHanJu_Color,
  },
  YooDongJae: {
    Name_kor: "유 동재",
    Name_eng: "YOO DONGJAE",
    Role: "Product designer",
    Email: "nlosnfin22@gmail.com",
    Link_insta: "https://www.instagram.com/devdz__/",
    Link_Behance: "",
    Link_Blog: "",
    Image_Color: YooDongJae_Color,
  },
  YuAJung: {
    Name_kor: "유 아정",
    Name_eng: "YU AJUNG",
    Role: "Product designer",
    Email: "jujusj0421@naver.com",
    Link_insta: "https://www.instagram.com/a_jung.e/",
    Link_Behance: "",
    Link_Blog: "",
    Image_Color: YuAJung_Color,
  },
  YuJiHui: {
    Name_kor: "유 지희",
    Name_eng: "YU JIHUI",
    Role: "Product designer",
    Email: "sarahyou@icloud.com",
    Link_insta: "",
    Link_Behance: "",
    Link_Blog: "",
    Image_Color: YuJiHui_Color,
  },
  LeeJongWon: {
    Name_kor: "이 종원",
    Name_eng: "LEE JONGWON",
    Role: "Product designer",
    Email: "idojwlee@gmail.com",
    Link_insta: "https://www.instagram.com/lee_jw_98/",
    Link_Behance: "",
    Link_Blog: "",
    Image_Color: LeeJongWon_Color,
  },
  LeeHongKyu: {
    Name_kor: "이 홍규",
    Name_eng: "LEE HONGKYU",
    Role: "Product designer",
    Email: "qwerty03096@gmail.com",
    Link_insta: "https://www.instagram.com/konkkiuu/",
    Link_Behance: "",
    Link_Blog: "",
    Image_Color: LeeHongKyu_Color,
  },
  JangSeoJin: {
    Name_kor: "장 서진",
    Name_eng: "JANG SEOJIN",
    Role: "Product designer",
    Email: "seojinswork@gmail.com",
    Link_insta: "https://www.instagram.com/seojins_work/",
    Link_Behance: "",
    Link_Blog: "",
    Image_Color: JangSeoJin_Color,
  },
  JunSeWon: {
    Name_kor: "전 세원",
    Name_eng: "JUN SEWON",
    Role: "Product designer",
    Email: "swjw0619@naver.com",
    Link_insta: "https://www.instagram.com/lustig_circle/",
    Link_Behance: "https://www.behance.net/swjw0619bbd3",
    Link_Blog: "",
    Image_Color: JunSeWon_Color,
  },
  JuYoonWoo: {
    Name_kor: "주 윤우",
    Name_eng: "JU YOONWOO",
    Role: "3D Graphic designer",
    Email: "wndbsdn28@naver.com",
    Link_insta: "https://www.instagram.com/j__yw/",
    Link_Behance: "",
    Link_Blog: "",
    Image_Color: JuYoonWoo_Color,
  },
  ChoiDaIn: {
    Name_kor: "최 다인",
    Name_eng: "CHOI DAIN",
    Role: "Product designer",
    Email: "dain2090@naver.com",
    Link_insta: "https://www.instagram.com/c_d_ai_n/",
    Link_Behance: "",
    Link_Blog: "",
    Image_Color: ChoiDaIn_Color,
  },
  ChoiJaeHo: {
    Name_kor: "최 재호",
    Name_eng: "CHOI JAEHO",
    Role: "Product designer",
    Email: "zmsdkdlwogh@naver.com",
    Link_insta: "https://www.instagram.com/jaeho.id/",
    Link_Behance: "",
    Link_Blog: "",
    Image_Color: ChoiJaeHo_Color,
  },
  HwangJuHyeok: {
    Name_kor: "황 주혁",
    Name_eng: "HWANG JUHYEOK",
    Role: "Product designer",
    Email: "hyeok12267@gmail.com",
    Link_insta: "https://www.instagram.com/jhjhjh__97/",
    Link_Behance: "https://www.behance.net/jhhwang122b2c2",
    Link_Blog: "",
    Image_Color: HwangJuHyeok_Color,
  },
  HongDongYoung: {
    Name_kor: "홍 동영",
    Name_eng: "HONG DONGYOUNG",
    Role: "Product designer",
    Email: "hy1527@gmail.com",
    Link_insta: "https://www.instagram.com/hong_d_y/",
    Link_Behance: "https://www.behance.net/hong_d_y",
    Link_Blog: "",
    Image_Color: HongDongYoung_Color,
  },
  JeonHaeIn: {
    Name_kor: "전 해인",
    Name_eng: "JEON HAEIN",
    Role: "Photographer.",
    Email: "hy1527@gmail.com",
    Link_insta: "https://www.instagram.com/im_haen/",
    Link_Behance: "",
    Link_Blog: "",
    Image_Color: "",
  },
  Jin: {
    Name_kor: "황 상진",
    Name_eng: "JIN",
    Role: "Developer.",
    Email: "aosdb5640@naver.com",
    Link_insta: "https://www.instagram.com/eudaimoniajin/",
    Link_Behance: "",
    Link_Blog: "",
    Image_Color: "",
  },
};

const AllDesignersData = [
  "KimGeonRyeong",
  "KimGoEun",
  "KimDongJun",
  "KimYaeJu",
  "KimYunHa",
  "KimJiHwan",
  " ",
  "NamMinJi",
  "ParkChangMin",
  "BakSeungEun",
  "SeoAReum",
  "ShinDongYeop",
  "ShinJiWoo",
  "SimMinSeop",
  "AnMyoungJi",
  "YangJiWon",
  "YangHyeSeon",
  " ",
  "WonHanJu",
  "YooDongJae",
  "YuAJung",
  "YuJiHui",
  "LeeJongWon",
  "LeeHongKyu",
  "JangSeoJin",
  "JunSeWon",
  "JuYoonWoo",
  " ",
  "ChoiDaIn",
  "ChoiJaeHo",
  "HwangJuHyeok",
  "HongDongYoung",
  "JeonHaeIn",
  "Jin",
];

const CommitteeDesignersData = [
  "KimDongJun",
  " ",
  "KimGeonRyeong",
  "LeeJongWon",
  "ShinDongYeop",
  "KimGoEun",
  "SeoAReum",
  "YuAJung",
  " ",
  "SimMinSeop",
  "HwangJuHyeok",
  "LeeHongKyu",
  "AnMyoungJi",
  "KimYaeJu",
  " ",
  "JuYoonWoo",
  "JeonHaeIn",
  "Jin",
];

const ProductDesignersData = [
  "KimGeonRyeong",
  "KimGoEun",
  "KimDongJun",
  "KimJiHwan",
  "BakSeungEun",
  "ShinDongYeop",
  "ShinJiWoo",
  "SimMinSeop",
  "AnMyoungJi",
  "YangHyeSeon",
  "WonHanJu",
  "YooDongJae",
  "YuAJung",
  "YuJiHui",
  "LeeJongWon",
  "LeeHongKyu",
  "JangSeoJin",
  "JunSeWon",
  "JuYoonWoo",
  "ChoiDaIn",
  "ChoiJaeHo",
  "HwangJuHyeok",
  "HongDongYoung",
  " ",
  "JeonHaeIn",
  "Jin",
];

const SpaceDesignersData = [
  "KimYaeJu",
  "KimYunHa",
  " ",
  "NamMinJi",
  "ParkChangMin",
  " ",
  "SeoAReum",
  "YangJiWon",
  "JeonHaeIn",
  "Jin",
];

export {
  DesignersData,
  AllDesignersData,
  CommitteeDesignersData,
  ProductDesignersData,
  SpaceDesignersData,
};
